name: Matrix demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        os: [ubuntu-latest, windows-latest]
        include:
          - node-version: 18
            os: ubuntu-latest
        exclude:
          - node-version: 12
            os: window-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - run: echo "Running on node ${{ matrix.node-version }} & os ${{ matrix.os }}"
